api/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('posts/', views.users, name='users'),
    path('posts/<int:pk>', views.users, name='user'),
]

 
    

blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('user/', include('user.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api/', include('api.urls')),

]

posts/urls.py
from django.urls import path
from posts.views import index,show,add,edit,delete,send_mails


urlpatterns =[
    path('', show.as_view(), name='show'),
    path('add/', add.as_view(), name='post.add'),
    path('edit/<int:pk>/', edit.as_view(), name='post.edit'),
    path('delete/<int:pk>/', delete.as_view(), name='post.delete'),
    path('mails/', send_mails, name='mails'),
]

posts/models.py
from django.db import models
from django import forms
from django.core import validators
from django.core.validators import ValidationError
from django.contrib.auth.models import User
from tinymce.widgets import TinyMCE
from tinymce.models import HTMLField


# Create your models here.
def min_length_check(val):
    if len(val) <= 10:
        raise ValidationError("%(val)s Must be Greater then 10", params={'val': val})


class Category(models.Model):
    title = models.CharField(validators=[min_length_check], max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager

    def __str__(self):
        return self.title

    def natural_key(self):
        return [self.id, self.title, self.created_at]

    class Meta:
        db_table = 'categories'
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['-created_at']


class Posts(models.Model):
    title = models.CharField(validators=[min_length_check], max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    thumbnail = models.FileField(upload_to='posts/', null=True)
    category = models.ManyToManyField(Category, default=0)
    content = HTMLField(validators=[min_length_check])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = models.Manager

    def __str__(self):
        return self.title


    class Meta:
        db_table = 'posts'
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-created_at']


class PostsForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['title', 'content', 'thumbnail', 'user', 'category']
        widgets ={
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Post Tiltle'}),
            'thumbnail': forms.FileInput(attrs={'class': 'form-control', 'multiple': True}),
            'content': TinyMCE(attrs={'class': 'form-control'}),
            'user':  forms.Select(attrs={'class': 'form-control'}),
            'category': forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled list-inline'}),
        }
        help_text={
            'title': 'Enter Title Here',
        }
        error_messages ={}
        labels={
            'title': 'Enter Post Title',
        }
    def clean(self):
        fields = self.cleaned_data
        keys = list(fields.keys())
        print(fields)
        if(len(fields['title']) <=10):
            raise ValidationError("%(val)s Must be Greater then 10", params={'val': keys[0]})
        if (len(fields['content']) <= 10):
            raise ValidationError("%(val)s Must be Greater then 10", params={'val': keys[1]})


class Gallery(models.Model):
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    images = models.FileField(upload_to="posts/", blank=True, null=True)

posts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from posts.models import Posts,Gallery,PostsForm,Category
from django.views.generic import TemplateView
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView
from django.http import JsonResponse
from django.core.mail import send_mail, send_mass_mail, mail_admins, mail_managers

class index(FormView):
    template_name = "index.html"
    form_class = PostsForm
    success_url = '/'

class show(TemplateView):
    template_name = "list_posts.html"
    model = Posts
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['object_list']= self.model.objects.all()
        return context


class add(CreateView):
    # model = Posts
    # fields = '__all__'
    form_class = PostsForm
    template_name = 'posts/posts_form.html'
    success_url = '/'
    
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        files = self.request.FILES.getlist('thumbnail')
        response = super().form_valid(form)
        for f in files:
            gallery = Gallery(post_id=self.object.pk, images=f)
            gallery.save()
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
                'success': "Record Successfully Added",
            }
            return JsonResponse(data)
        else:
            return response

class edit(UpdateView):
    # model = Posts
    # fields = '__all__'
    form_class =PostsForm
    success_url = '/'

    def get_queryset(self):
        id = self.kwargs['pk']
        return Posts.objects.filter(pk=id)
    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        Gallery.objects.filter(post_id=self.kwargs['pk']).delete()
        files = self.request.FILES.getlist('thumbnail')
        response = super().form_valid(form)
        for f in files:
            gallery = Gallery(post_id=self.object.pk, images=f)
            gallery.save()
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
                'success': "Record Successfully Updated",
            }
            return JsonResponse(data)
        else:
            return response

class delete(DeleteView):
    model = Posts
    success_url = reverse_lazy('show')

def send_mails(request):
    mail_admins('Error i Found', 'we have found some errors', fail_silently=False)
    mail_managers('Error i Found', 'we have found some errors', fail_silently=False)
    return HttpResponse("Emails send to Admin")


    # Mass mailing Using send_mass_mail function

    # mail1 = ("Test Subject", "Hello, How are you? This is text",'admin@admin.com',['test@test.com'],
    # html_message="<h2>Hello, How are you? this is html</h2>")

    # mail2 = ("Test Subject", "Hello, How are you? This is text",'admin@admin.com',['test@test.com'],
    # html_message="<h2>Hello, How are you? this is html</h2>")

    # mail = send_mass_mail((mail1, mail2), fail_silently=False)
    # if mail:
    #     return HttpResponse(mail)
    # else:
    #     raise Exception("Error")

    # single mail using send_mail function

    # mail = send_mail("Test Subject", "Hello, How are you? This is text",'admin@admin.com',['test@test.com'],
    # fail_silently=False,html_message="<h2>Hello, How are you? this is html</h2>")

    # if mail:
    #     return HttpResponse(mail)
    # else:
    #     raise Exception("Error")

    # email send to the multiple people using send_mail function

    # mail1 = send_mail("Test Subject", "Hello, How are you? This is text",'admin@admin.com',['test@test.com'],
    # fail_silently=False,html_message="<h2>Hello, How are you? this is html</h2>")

    # mail2 = send_mail("Test Subject", "Hello, How are you? This is text",'admin@admin.com',['test@test.com'],
    # fail_silently=False,html_message="<h2>Hello, How are you? this is html</h2>")

    # if mail1 and mail2:
    #     return HttpResponse(mail)
    # else:
    #     raise Exception("Error")

   

posts/templates/class_view.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>class based view</title>
</head>
<body>
    <h1>Class based view from views.py </h1>
    <div>
    <form action="/cbview/" method="POST" class="form-row" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="d-block">
        {% if form.title.errors %}
        {% for err_title in from.title.errors %}
        <p>Title{{ err_title | escape }}</p>
        {% endfor %}
        {% endif %}
        {% if form.content.errors %}
        {% for err_content in from.content.errors %}
        <p>Content{{ err_content | escape }}</p>
        {% endfor %}
        {% endif %}
        {% if form.thumbnail.errors %}
        {% for err_thumbnail in from.thumbnail.errors %}
        <p>Thumbnail{{ err_thumbnail | escape }}</p>
        {% endfor %}
        {% endif %}
        {% if form.errors %}
            {% for errors in form.non_field_errors %}
                <p>{{errors | escape }}</p>
            {% endfor %}
        {% endif %}
        {% for f in form %}
        <div class="form-group">
            {{f.label_tag}}

            {{f}}
        </div>
        {% endfor %}
    </div>
    <input class="btn btn-primary" type="submit" value="Add Post">
</form>
    </div>
<div>
    {% for row in object_list %}
    <h2>{{row.title}}</h2>
    <p>{{row.content}} - <samall>{{row.created_at}}</samall></p>
     <img src="{% static row.thumbnail %}" width="50">
    <p><h2>Gallery Images</h2></p>
    <p>
        {% for g in row.gallery_set.all %}
            <img src="{% static g.images %}" width="50">
        {% endfor %}
    </p>
    <p class="small">{{row.user.username}}</p>
    <ul>
        {% for cat in row.category.all %}
        <li>
            {{cat}}
        </li>
        {% endfor %}
    </ul>
    {% endfor %}
</div>
<div>
    <h2>Categories</h2>
    {% for cats in categories %}
    <h4>{{cats.title}}</h4>
        {% for cat in cats.categories.all %}
            {{cat}}
        {% endfor %}
    {% endfor %}
</div>
</body>
</html>

posts/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
   <script type="text/javascript" src="static /js/tiny_mce/tiny_mce.js"></script>
   <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.js' integrity='sha512-jKxp7JHEN6peEmzmg6a7XJBORNTB0ITD2Pi+6FUkc16PCaNAJX2ahZ1ejn1p1uY37Pxyirn/0OMNZbITbEg3jw==' crossorigin='anonymous'></script>
    <script type="text/javascript">
        tinyMCE.init({
        'selector' : 'textareas',
        "theme" : "simple"
        });
    </script>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

posts/templates/list_posts.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>List of Posts</title>
</head>
<body>
    <h1>list of Posts </h1>
<div>
    <a href="/add/">Add new Post</a>
    {% if object_list.count > 0 %}
    {% for row in object_list %}
    <h2>{{row.title}}</h2>
            {{row.content}}
    <p>{{row.content}} - <samall>{{row.created_at}}</samall></p>
     <img src="{% static row.thumbnail %}" width="50">
    <p><h2>Gallery Images</h2></p>
    <p>
        {% for g in row.gallery_set.all %}
            <img src="{% static g.images %}" width="50">
        {% endfor %}
    </p>
    <p class="small">{{row.user.username}}</p>
    <ul>
        {% for cat in row.category.all %}

        <li>
            {{cat}}
        </li>
        {% endfor %}
    </ul>
            <p><a href="/edit/{{row.id}}/">Edit Post</a> | <a href="/delete/{{row.id}}/">Delete Post</a> </p>
    {% endfor %}
    {% endif %}
</div>
<!--<div>-->
<!--    <h2>Categories</h2>-->
<!--    {% for cats in categories %}-->
<!--    <h4>{{cats.title}}</h4>-->
<!--        {% for cat in cats.categories.all %}-->

<!--            {{cat}}-->
<!--        {% endfor %}-->
<!--    {% endfor %}-->
<!--</div>-->
</body>
</html>